config/routes.rb
Rails.application.routes.draw do

	get 'sessions/new'

	root 'events#index'
	get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

	resources :attendees, only: [:create]
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
	belongs_to :attended_event, class_name: 'Event'
  belongs_to :guest, class_name: 'User'
	validates :attended_event_id, presence: true
	validates :guest_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :host, class_name: 'User'
  has_many :attendees, foreign_key: :attended_event_id
  has_many :guests, through: :attendees, source: :guest
  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :host_id, presence: true
  validates :location, presence: true
  validates :date, presence: true

  scope :past, (-> { where('date < ?', Date.today) })
  scope :upcoming, (-> { where('date >= ?', Date.today) })
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events, foreign_key: 'host_id', class_name: 'Event'
  has_many :attendees, foreign_key: :guest_id
  has_many :attended_events, through: :attendees, source: :attended_event
  validates :name, presence: true
  validates :email, presence: true

  def upcoming_events
    attended_events.where('date >= ?', Date.today)
  end

  def past_events
    attended_events.where('date < ?', Date.today)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
	def create
		event = Event.find(params[:attendee][:attended_event_id])
    if event.guests.include?(current_user)
      flash[:danger] = "You are already attending #{event.title}."
    else
      current_user.attendees.create(attended_event: event)
      flash[:success] = "You are now attending #{event.title}."
    end
    redirect_to event
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@past_events = Event.past
    @upcoming_events = Event.upcoming
	end

	def new
		@event = Event.new
	end

	def create
		@event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'Event created successsfully!'
      redirect_to root_path
    else
      flash.now[:error] = 'Whoops! Something went wrong.'
      render 'new'
    end
	end

	def show
		@event = Event.find(params[:id])
	end

	private

		def event_params
			params.require(:event).permit(:title, :description, :date, :location)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if @user
  		log_in @user
  		flash[:notice] = "You have successfully logged in."
  		redirect_to root_url
  	else
  		flash.now[:danger] = 'Invalid user.'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:info] = "Success! You have created an account."
			log_in @user
			redirect_to action: "show", id: @user.id
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@events = @user.events
		@upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
	end

	private
		def user_params
			params.require(:user).permit(:name, :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<a href= <%= event_path(event.id) %> class="list-group-item">
	<h4 class="list-group-item-heading"> <%= event.title %> </h4>
	<p class="list-group-item-text">Location: <%= event.location %></p>
	<p class="list-group-item-text"><%= event.description %></p>
	<p class="list-group-item-text">
		Hosted By: <%=event.host.name%> on <%= event.date %>
	</p>
</a>

app/views/events/index.html.erb
<h1>All Events</h1>
<div class="row">
  <h3>Upcoming Events</h3>
    <div class="container">
      <div class="list-group">
        <div class="events">
          <%= render @upcoming_events %>
        </div>
      </div>
    </div>
  <h3>Past Events</h3>
    <div class="container">
      <div class="list-group">
        <div class="events">
          <%= render @past_events %>
        </div>
      </div>
    </div>
</div>

app/views/events/new.html.erb
<h1>Create an Event</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @event do |f| %>
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title %>

      <%= f.label :description, 'Description' %>
      <%= f.text_field :description %>

      <%= f.label :date, 'Date' %>
      <%= f.date_field :date %>

      <%= f.label :location, 'Location' %>
      <%= f.text_field :location %>

      <%= f.submit 'Create event', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2" id="event_view">
    <p><%= @event.description %></p>
    <h6>Hosted by: <%=@event.host.name%></h6>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <% if logged_in? && @event.host_id != current_user.id %>
        <%= form_for(current_user.attendees.build(attended_event_id: @event_id)) do |f| %>
          <%= f.hidden_field :attended_event_id, value: @event.id %>
          <%= f.submit 'Attend', class: 'btn btn-small btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <h4>Date</h4>
      <%= @event.date %>
    </div>
    <div class="col-md-2">
      <h4>Location</h4>
      <%= @event.location %>
    </div>
    <div class="col-md-2">
      <h4>Attending</h4>
      <ul>
        <% @event.guests.each do |guest| %>
          <li>
            <%= link_to guest.name, guest %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Coded by <a href="https://github.com/MarshallM1">B.Morris</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private Events", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Events", events_path %></li>
        <% if logged_in? %>
          <li><%= link_to current_user.name, user_path(current_user.id)%>
          <li><%= link_to "Log out", logout_path, method: :delete %>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="row">

  <h3>Hosted Events</h3>
    <% if logged_in? && @user == current_user %>
      <%= link_to '(Create a new event)', new_event_path %>
    <% end %>

    <div class="container">
    	<div class="list-group">
    		<div class="events">
      		<%= render @events %>
    		</div>
    	</div>
    </div>

    <h3>Upcoming Events</h3>
    <div class="container">
    	<div class="list-group">
    		<div class="events">
      		<%= render @upcoming_events %>
    		</div>
    	</div>
    </div>

    <h3>Past Events</h3>
    <div class="container">
    	<div class="list-group">
    		<div class="events">
      		<%= render @past_events %>
    		</div>
    	</div>
    </div>
</div>